spring:
  application:
    name: backend-user

  datasource:
    url: jdbc:postgresql://localhost:5432/backend_user
    username: postgres
    password: NuevaPassword123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

server:
  port: 8081
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    com.TecUnify: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Configuraci贸n de CORS
cors:
  allowed-origins: "http://localhost:5173,http://localhost:3000"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true

# Configuraci贸n de la aplicaci贸n
app:
  name: TecUnify
  version: 1.2.0
  description: Sistema de reservas de espacios tecnol贸gicos